% Takes a binary image with a solid object and returns only the borders
% (returns only 1's that are touching 0's)
function out = onlyTheSurface(IMG)

inv = ~IMG;
edges = IMG & (circshift(inv, [1 0 0]) | ... %these lines keep only the border of the filled in sphere
               circshift(inv, [0 1 0]) | ...
               circshift(inv, [0 0 1]) | ...
               circshift(inv, [-1 0 0]) | ...
               circshift(inv, [0 -1 0]) | ...
               circshift(inv, [0 0 -1]) | ...
               circshift(inv, [0 1 0]) | ...
               circshift(inv, [0 1 0]) | ...
               circshift(inv, [0 1 0]));
out = edges;
end