function out = sphere(radius)

[X, Y, Z] = meshgrid(-radius:radius, -radius:radius, -radius:radius);
sph = (X .^ 2 + Y .^ 2 + Z .^ 2) <= radius^2; %sph is a filled in sphere
inv = ~sph;

edges = sph & (circshift(inv, [1 0 0]) | ... %these lines keep only the border of the filled in sphere
               circshift(inv, [0 1 0]) | ...
               circshift(inv, [0 0 1]) | ...
               circshift(inv, [-1 0 0]) | ...
               circshift(inv, [0 -1 0]) | ...
               circshift(inv, [0 0 -1]) | ...
               circshift(inv, [0 1 0]) | ...
               circshift(inv, [0 1 0]) | ...
               circshift(inv, [0 1 0]));
                   
out = edges;